version: '3'
services:
  app:
    image: nt3awno:latest
    container_name: laravel_app
    volumes:
      - ./laravel-app:/var/www
  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
